var annotated_dup =
[
    [ "foleys", "namespacefoleys.html", [
      [ "CameraManager", null, [
        [ "Pimpl", "structfoleys_1_1CameraManager_1_1Pimpl.html", "structfoleys_1_1CameraManager_1_1Pimpl" ]
      ] ],
      [ "CameraReceiver", null, [
        [ "Pimpl", "structfoleys_1_1CameraReceiver_1_1Pimpl.html", "structfoleys_1_1CameraReceiver_1_1Pimpl" ]
      ] ],
      [ "AudioClip", "classfoleys_1_1AudioClip.html", "classfoleys_1_1AudioClip" ],
      [ "AudioFifo", "classfoleys_1_1AudioFifo.html", "classfoleys_1_1AudioFifo" ],
      [ "AudioMixer", "classfoleys_1_1AudioMixer.html", "classfoleys_1_1AudioMixer" ],
      [ "AudioParameterAutomation", "classfoleys_1_1AudioParameterAutomation.html", "classfoleys_1_1AudioParameterAutomation" ],
      [ "AudioPluginManager", "classfoleys_1_1AudioPluginManager.html", "classfoleys_1_1AudioPluginManager" ],
      [ "AudioProcessorAdapter", "structfoleys_1_1AudioProcessorAdapter.html", "structfoleys_1_1AudioProcessorAdapter" ],
      [ "AudioStreamSettings", "structfoleys_1_1AudioStreamSettings.html", "structfoleys_1_1AudioStreamSettings" ],
      [ "AudioStrip", "classfoleys_1_1AudioStrip.html", "classfoleys_1_1AudioStrip" ],
      [ "AVClip", "classfoleys_1_1AVClip.html", "classfoleys_1_1AVClip" ],
      [ "AVFormat", "structfoleys_1_1AVFormat.html", "structfoleys_1_1AVFormat" ],
      [ "AVFormatManager", "classfoleys_1_1AVFormatManager.html", "classfoleys_1_1AVFormatManager" ],
      [ "AVReader", "classfoleys_1_1AVReader.html", "classfoleys_1_1AVReader" ],
      [ "AVWriter", "classfoleys_1_1AVWriter.html", "classfoleys_1_1AVWriter" ],
      [ "ClipDescriptor", "classfoleys_1_1ClipDescriptor.html", "classfoleys_1_1ClipDescriptor" ],
      [ "ClipRenderer", "classfoleys_1_1ClipRenderer.html", "classfoleys_1_1ClipRenderer" ],
      [ "ColourCurve", "classfoleys_1_1ColourCurve.html", "classfoleys_1_1ColourCurve" ],
      [ "ColourCurveVideoProcessor", "classfoleys_1_1ColourCurveVideoProcessor.html", "classfoleys_1_1ColourCurveVideoProcessor" ],
      [ "ComposedClip", "classfoleys_1_1ComposedClip.html", "classfoleys_1_1ComposedClip" ],
      [ "ControllableBase", "classfoleys_1_1ControllableBase.html", "classfoleys_1_1ControllableBase" ],
      [ "D3DManager", "classfoleys_1_1D3DManager.html", "classfoleys_1_1D3DManager" ],
      [ "DefaultAudioMixer", "classfoleys_1_1DefaultAudioMixer.html", "classfoleys_1_1DefaultAudioMixer" ],
      [ "FFmpegWriter", "classfoleys_1_1FFmpegWriter.html", "classfoleys_1_1FFmpegWriter" ],
      [ "FilmStrip", "classfoleys_1_1FilmStrip.html", "classfoleys_1_1FilmStrip" ],
      [ "ImageClip", "classfoleys_1_1ImageClip.html", "classfoleys_1_1ImageClip" ],
      [ "KeyframeComparator", "structfoleys_1_1KeyframeComparator.html", "structfoleys_1_1KeyframeComparator" ],
      [ "LevelMeter", "classfoleys_1_1LevelMeter.html", "classfoleys_1_1LevelMeter" ],
      [ "LevelMeterLookAndFeel", "classfoleys_1_1LevelMeterLookAndFeel.html", "classfoleys_1_1LevelMeterLookAndFeel" ],
      [ "LevelMeterSource", "classfoleys_1_1LevelMeterSource.html", "classfoleys_1_1LevelMeterSource" ],
      [ "MediaFoundationFormat", "structfoleys_1_1MediaFoundationFormat.html", "structfoleys_1_1MediaFoundationFormat" ],
      [ "MediaFoundationReader", "classfoleys_1_1MediaFoundationReader.html", "classfoleys_1_1MediaFoundationReader" ],
      [ "MFScopedPointer", "classfoleys_1_1MFScopedPointer.html", "classfoleys_1_1MFScopedPointer" ],
      [ "MovieClip", "classfoleys_1_1MovieClip.html", "classfoleys_1_1MovieClip" ],
      [ "OutlineBuffer", "classfoleys_1_1OutlineBuffer.html", "classfoleys_1_1OutlineBuffer" ],
      [ "ParameterAutomation", "classfoleys_1_1ParameterAutomation.html", "classfoleys_1_1ParameterAutomation" ],
      [ "ProcessorController", "classfoleys_1_1ProcessorController.html", "classfoleys_1_1ProcessorController" ],
      [ "ProcessorParameter", "classfoleys_1_1ProcessorParameter.html", "classfoleys_1_1ProcessorParameter" ],
      [ "ProcessorParameterFloat", "classfoleys_1_1ProcessorParameterFloat.html", "classfoleys_1_1ProcessorParameterFloat" ],
      [ "ProcessorState", "classfoleys_1_1ProcessorState.html", "classfoleys_1_1ProcessorState" ],
      [ "Size", "structfoleys_1_1Size.html", "structfoleys_1_1Size" ],
      [ "SoftwareVideoMixer", "classfoleys_1_1SoftwareVideoMixer.html", "classfoleys_1_1SoftwareVideoMixer" ],
      [ "SoftwareView", "classfoleys_1_1SoftwareView.html", "classfoleys_1_1SoftwareView" ],
      [ "StereoFieldBuffer", "classfoleys_1_1StereoFieldBuffer.html", "classfoleys_1_1StereoFieldBuffer" ],
      [ "StereoFieldComponent", "classfoleys_1_1StereoFieldComponent.html", "classfoleys_1_1StereoFieldComponent" ],
      [ "StreamTypes", "classfoleys_1_1StreamTypes.html", "classfoleys_1_1StreamTypes" ],
      [ "TimeCodeAware", "classfoleys_1_1TimeCodeAware.html", "classfoleys_1_1TimeCodeAware" ],
      [ "VideoBufferLock", "classfoleys_1_1VideoBufferLock.html", "classfoleys_1_1VideoBufferLock" ],
      [ "VideoEngine", "classfoleys_1_1VideoEngine.html", "classfoleys_1_1VideoEngine" ],
      [ "VideoFifo", "classfoleys_1_1VideoFifo.html", "classfoleys_1_1VideoFifo" ],
      [ "VideoFrame", "structfoleys_1_1VideoFrame.html", "structfoleys_1_1VideoFrame" ],
      [ "VideoMixer", "classfoleys_1_1VideoMixer.html", "classfoleys_1_1VideoMixer" ],
      [ "VideoParameterAutomation", "classfoleys_1_1VideoParameterAutomation.html", "classfoleys_1_1VideoParameterAutomation" ],
      [ "VideoPluginManager", "classfoleys_1_1VideoPluginManager.html", "classfoleys_1_1VideoPluginManager" ],
      [ "VideoProcessor", "classfoleys_1_1VideoProcessor.html", "classfoleys_1_1VideoProcessor" ],
      [ "VideoProcessorAdapter", "structfoleys_1_1VideoProcessorAdapter.html", "structfoleys_1_1VideoProcessorAdapter" ],
      [ "VideoStreamSettings", "structfoleys_1_1VideoStreamSettings.html", "structfoleys_1_1VideoStreamSettings" ],
      [ "VideoView", "classfoleys_1_1VideoView.html", "classfoleys_1_1VideoView" ]
    ] ],
    [ "MainComponent", "classMainComponent.html", "classMainComponent" ],
    [ "MainContentComponent", "classMainContentComponent.html", "classMainContentComponent" ],
    [ "MultiCamTestApplication", "classMultiCamTestApplication.html", "classMultiCamTestApplication" ],
    [ "OSDComponent", "classOSDComponent.html", "classOSDComponent" ],
    [ "VideoComponentWithDropper", "classVideoComponentWithDropper.html", "classVideoComponentWithDropper" ],
    [ "VideoPlayerApplication", "classVideoPlayerApplication.html", "classVideoPlayerApplication" ],
    [ "VideoPreview", "classVideoPreview.html", null ]
];