foleys_video_engine: SoftwareView Class Reference
SoftwareView Class Reference
#include <foleys_SoftwareView.h>
Public Member Functions
SoftwareView ()
~SoftwareView () override
void setClip (std::shared_ptr< AVClip > clip) override
std::shared_ptr< AVClip > getClip () const override
void paint (juce::Graphics &g) override
void setContinuousRepaint (int hz) override
void timerCallback () override
void timecodeChanged (int64_t count, double seconds) override
Listen to this callback to get notified, when the time code changes.
Public Member Functions inherited from VideoView
VideoView ()=default
virtual ~VideoView ()=default
Public Member Functions inherited from TimeCodeAware::Listener
virtual ~Listener ()=default
Destructor.
Constructor & Destructor Documentation
SoftwareView()
SoftwareView ()
~SoftwareView()
~SoftwareView () override
Member Function Documentation
setClip()
void setClip (std::shared_ptr< AVClip > clip) override virtual
Implements VideoView.
Referenced by MainComponent::MainComponent(), and MainContentComponent::openFile().
getClip()
std::shared_ptr< AVClip > getClip () const override virtual
Implements VideoView.
paint()
void paint (juce::Graphics & g) override
setContinuousRepaint()
void setContinuousRepaint (int hz) override virtual
Implements VideoView.
Referenced by MainComponent::changeListenerCallback(), and VideoComponentWithDropper::VideoComponentWithDropper().
timerCallback()
void timerCallback () override
timecodeChanged()
void timecodeChanged (int64_t count, double seconds) override virtual
Listen to this callback to get notified, when the time code changes.
This is most useful to redraw the display or encode the next frame
Implements TimeCodeAware::Listener.
The documentation for this class was generated from the following files:
foleys_SoftwareView.h
foleys_SoftwareView.cpp