foleys_video_engine: MFScopedPointer< T > Class Template Reference
MFScopedPointer< T > Class Template Reference
#include <foleys_Helpers_Win.h>
Public Member Functions
MFScopedPointer ()=default
~MFScopedPointer ()
T * get ()
Return a raw pointer to the managed pointee.
T ** getPointer ()
Returns the pointer, so a creation method can reset the pointer variable as well.
T * operator-> ()
void reset (T *p=nullptr)
Set a new pointee.
operator bool () const
Returns true if it has a pointee or false if it points to nullptr.
Constructor & Destructor Documentation
MFScopedPointer()
template<typename T > MFScopedPointer () default
~MFScopedPointer()
template<typename T > ~MFScopedPointer ()
References MFScopedPointer< T >::reset().
Member Function Documentation
get()
template<typename T > T * get ()
Return a raw pointer to the managed pointee.
Referenced by CloneVideoMediaType(), CreatePhotoMediaType(), Pimpl::getAvailableResolutions(), D3DManager::getDeviceManager(), MediaFoundationReader::Pimpl::getStillImage(), MediaFoundationReader::Pimpl::Pimpl(), MediaFoundationReader::Pimpl::readNewData(), Pimpl::setResolutionIndex(), and D3DManager::~D3DManager().
getPointer()
template<typename T > T ** getPointer ()
Returns the pointer, so a creation method can reset the pointer variable as well.
Make sure it is nullptr before, because you cannot know if the creation succeeds or not.
Referenced by CloneVideoMediaType(), CreatePhotoMediaType(), Pimpl::getAvailableResolutions(), MediaFoundationReader::Pimpl::getStillImage(), Pimpl::SampleCallback::OnSample(), MediaFoundationReader::Pimpl::Pimpl(), MediaFoundationReader::Pimpl::readNewData(), and Pimpl::setResolutionIndex().
operator->()
template<typename T > T * operator-> ()
reset()
template<typename T > void reset (T * p = nullptr)
Set a new pointee.
If there was a managed pointee it will call Release and forget it
Referenced by MediaFoundationReader::Pimpl::getStillImage(), and MFScopedPointer< T >::~MFScopedPointer().
operator bool()
template<typename T > operator bool () const
Returns true if it has a pointee or false if it points to nullptr.
The documentation for this class was generated from the following file:
foleys_Helpers_Win.h