foleys_video_engine: ClipDescriptor::Listener Class Reference
ClipDescriptor::Listener Class Reference abstract
Listener to be notified of changes in this ClipDescriptor, especially the removal of a ProcessorController.
#include <foleys_ClipDescriptor.h>
Public Member Functions
virtual ~Listener ()=default
virtual void processorControllerAdded ()=0
virtual void processorControllerToBeDeleted (const ProcessorController *)=0
Detailed Description
Listener to be notified of changes in this ClipDescriptor, especially the removal of a ProcessorController.
Constructor & Destructor Documentation
~Listener()
virtual ~Listener () virtual default
Member Function Documentation
processorControllerAdded()
virtual void processorControllerAdded () pure virtual
Referenced by ClipDescriptor::addAudioProcessor(), and ClipDescriptor::addVideoProcessor().
processorControllerToBeDeleted()
virtual void processorControllerToBeDeleted (const ProcessorController *) pure virtual
Referenced by ClipDescriptor::removeAudioProcessor(), ClipDescriptor::removeProcessor(), ClipDescriptor::removeVideoProcessor(), and ClipDescriptor::~ClipDescriptor().
The documentation for this class was generated from the following file:
foleys_ClipDescriptor.h