foleys_video_engine: ProcessorParameterFloat Class Reference
ProcessorParameterFloat Class Reference
This is a floating point (double) parameter to configure and automate your VideoProcessors.
#include <foleys_ProcessorParameter.h>
Public Member Functions
ProcessorParameterFloat (const juce::Identifier &paramID, const juce::String &name, juce::NormalisableRange< double > range, double defaultValue, std::function< juce::String(double, int)> valueToText=nullptr, std::function< double(const juce::String &)> textToValue=nullptr)
const int getNumSteps () const override
double * getRawParameterValue () override
double getNormalisedValue () const override
double getRealValue () const override
double getDefaultValue () const override
Returns the default value in normalised for the automation to initialise.
void setNormalisedValue (double value) override
void setRealValue (double value) override
double normaliseValue (double unnormalised) const override
double unNormaliseValue (double normalised) const override
juce::String getText (float normalisedValue, int numDigits=0) const override
double getValueForText (const juce::String &text) const override
Public Member Functions inherited from ProcessorParameter
ProcessorParameter (const juce::Identifier &paramID, const juce::String &name)
This defines a parameter to be used in Processors like the VideoProcessor.
virtual ~ProcessorParameter ()=default
const juce::Identifier & getParameterID () const
const juce::String & getName () const
juce::NamedValueSet & getProperties ()
void setParameterIndex (int index)
int getParameterIndex () const
void beginGesture ()
void endGesture ()
bool isGestureInProgress () const
void addListener (Listener *listener)
void removeListener (Listener *listener)
void sendUpdateNotification ()
Detailed Description
This is a floating point (double) parameter to configure and automate your VideoProcessors.
Constructor & Destructor Documentation
ProcessorParameterFloat()
ProcessorParameterFloat (const juce::Identifier & paramID, const juce::String & name, juce::NormalisableRange< double > range, double defaultValue, std::function< juce::String(double, int)> valueToText = nullptr, std::function< double(const juce::String &)> textToValue = nullptr)
Member Function Documentation
getNumSteps()
const int getNumSteps () const override virtual
Implements ProcessorParameter.
getRawParameterValue()
double * getRawParameterValue () override virtual
Implements ProcessorParameter.
getNormalisedValue()
double getNormalisedValue () const override virtual
Implements ProcessorParameter.
getRealValue()
double getRealValue () const override virtual
Implements ProcessorParameter.
getDefaultValue()
double getDefaultValue () const override virtual
Returns the default value in normalised for the automation to initialise.
Implements ProcessorParameter.
References ProcessorParameterFloat::normaliseValue().
setNormalisedValue()
void setNormalisedValue (double value) override virtual
Implements ProcessorParameter.
References ProcessorParameter::sendUpdateNotification(), and ProcessorParameterFloat::unNormaliseValue().
setRealValue()
void setRealValue (double value) override virtual
Implements ProcessorParameter.
References ProcessorParameter::sendUpdateNotification().
normaliseValue()
double normaliseValue (double unnormalised) const override virtual
Implements ProcessorParameter.
Referenced by ProcessorParameterFloat::getDefaultValue().
unNormaliseValue()
double unNormaliseValue (double normalised) const override virtual
Implements ProcessorParameter.
Referenced by ProcessorParameterFloat::setNormalisedValue().
getText()
juce::String getText (float normalisedValue, int numDigits = 0) const override virtual
Implements ProcessorParameter.
getValueForText()
double getValueForText (const juce::String & text) const override virtual
Implements ProcessorParameter.
The documentation for this class was generated from the following files:
foleys_ProcessorParameter.h
foleys_ProcessorParameter.cpp