foleys_video_engine: MainContentComponent Class Reference
MainContentComponent Class Reference
Public Member Functions
MainContentComponent ()
~MainContentComponent () override
void prepareToPlay (int samplesPerBlockExpected, double newSampleRate) override
void getNextAudioBlock (const juce::AudioSourceChannelInfo &bufferToFill) override
void releaseResources () override
void timecodeChanged (int64_t, double seconds) override
Listen to this callback to get notified, when the time code changes.
void openFile (juce::File name)
void openFile ()
void paint (juce::Graphics &g) override
void resized () override
bool keyPressed (const juce::KeyPress &key) override
Public Member Functions inherited from TimeCodeAware::Listener
virtual ~Listener ()=default
Destructor.
Constructor & Destructor Documentation
MainContentComponent()
MainContentComponent ()
References OSDComponent::camera, OSDComponent::ffwd, VideoEngine::getFormatManager(), VideoComponentWithDropper::onFileDropped, OSDComponent::open, openFile(), OSDComponent::pause, OSDComponent::play, AVFormatManager::registerFormat(), OSDComponent::seekBar, and OSDComponent::stop.
~MainContentComponent()
~MainContentComponent () override
Member Function Documentation
prepareToPlay()
void prepareToPlay (int samplesPerBlockExpected, double newSampleRate) override
getNextAudioBlock()
void getNextAudioBlock (const juce::AudioSourceChannelInfo & bufferToFill) override
releaseResources()
void releaseResources () override
timecodeChanged()
void timecodeChanged (int64_t count, double seconds) override virtual
Listen to this callback to get notified, when the time code changes.
This is most useful to redraw the display or encode the next frame
Implements TimeCodeAware::Listener.
References OSDComponent::seekBar.
openFile() [1/2]
void openFile (juce::File name)
References VideoEngine::createClipFromFile(), OSDComponent::seekBar, FilmStrip::setClip(), SoftwareView::setClip(), OSDComponent::setClip(), and FilmStrip::setStartAndEnd().
openFile() [2/2]
void openFile ()
References openFile().
Referenced by MainContentComponent(), and openFile().
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
keyPressed()
bool keyPressed (const juce::KeyPress & key) override
The documentation for this class was generated from the following file:
VideoPlayer/Source/MainComponent.cpp