foleys_video_engine: ProcessorParameter Class Reference
ProcessorParameter Class Reference abstract
This is the base class for parameters to configure and automate your VideoProcessors.
#include <foleys_ProcessorParameter.h>
Classes
class Listener
Public Member Functions
ProcessorParameter (const juce::Identifier &paramID, const juce::String &name)
This defines a parameter to be used in Processors like the VideoProcessor.
virtual ~ProcessorParameter ()=default
const juce::Identifier & getParameterID () const
const juce::String & getName () const
juce::NamedValueSet & getProperties ()
void setParameterIndex (int index)
int getParameterIndex () const
virtual const int getNumSteps () const =0
virtual double * getRawParameterValue ()=0
virtual double getNormalisedValue () const =0
virtual double getRealValue () const =0
virtual double normaliseValue (double unnormalised) const =0
virtual double unNormaliseValue (double normalised) const =0
virtual double getDefaultValue () const =0
Returns the default value in normalised for the automation to initialise.
virtual void setNormalisedValue (double value)=0
virtual void setRealValue (double value)=0
virtual juce::String getText (float normalisedValue, int numDigits=0) const =0
virtual double getValueForText (const juce::String &text) const =0
void beginGesture ()
void endGesture ()
bool isGestureInProgress () const
void addListener (Listener *listener)
void removeListener (Listener *listener)
void sendUpdateNotification ()
Detailed Description
This is the base class for parameters to configure and automate your VideoProcessors.
Constructor & Destructor Documentation
ProcessorParameter()
ProcessorParameter (const juce::Identifier & paramID, const juce::String & name)
This defines a parameter to be used in Processors like the VideoProcessor.
Parameters
paramID an unique identifier for host and your processor to identify the parameter
name the name the host will use to display the automation
~ProcessorParameter()
virtual ~ProcessorParameter () virtual default
Member Function Documentation
getParameterID()
const juce::Identifier & getParameterID () const
getName()
const juce::String & getName () const
Referenced by VideoParameterAutomation::getName().
getProperties()
juce::NamedValueSet & getProperties ()
Referenced by VideoParameterAutomation::getParameterProperties().
setParameterIndex()
void setParameterIndex (int index)
getParameterIndex()
int getParameterIndex () const
Referenced by VideoParameterAutomation::getParameterIndex().
getNumSteps()
virtual const int getNumSteps () const pure virtual
Implemented in ProcessorParameterFloat.
Referenced by VideoParameterAutomation::getNumSteps().
getRawParameterValue()
virtual double * getRawParameterValue () pure virtual
Implemented in ProcessorParameterFloat.
getNormalisedValue()
virtual double getNormalisedValue () const pure virtual
Implemented in ProcessorParameterFloat.
getRealValue()
virtual double getRealValue () const pure virtual
Implemented in ProcessorParameterFloat.
Referenced by ProcessorParameter::sendUpdateNotification().
normaliseValue()
virtual double normaliseValue (double unnormalised) const pure virtual
Implemented in ProcessorParameterFloat.
Referenced by VideoParameterAutomation::addRealKeyframe(), VideoParameterAutomation::setKeyframesWithRealValues(), VideoParameterAutomation::setRealValue(), and VideoParameterAutomation::setRealValue().
unNormaliseValue()
virtual double unNormaliseValue (double normalised) const pure virtual
Implemented in ProcessorParameterFloat.
Referenced by VideoParameterAutomation::getRealValueForTime().
getDefaultValue()
virtual double getDefaultValue () const pure virtual
Returns the default value in normalised for the automation to initialise.
Implemented in ProcessorParameterFloat.
setNormalisedValue()
virtual void setNormalisedValue (double value) pure virtual
Implemented in ProcessorParameterFloat.
Referenced by VideoParameterAutomation::updateProcessor().
setRealValue()
virtual void setRealValue (double value) pure virtual
Implemented in ProcessorParameterFloat.
getText()
virtual juce::String getText (float normalisedValue, int numDigits = 0) const pure virtual
Implemented in ProcessorParameterFloat.
Referenced by VideoParameterAutomation::getText().
getValueForText()
virtual double getValueForText (const juce::String & text) const pure virtual
Implemented in ProcessorParameterFloat.
Referenced by VideoParameterAutomation::getValueForText().
beginGesture()
void beginGesture ()
References ProcessorParameter::Listener::gestureStarted().
endGesture()
void endGesture ()
References ProcessorParameter::Listener::gestureFinished().
isGestureInProgress()
bool isGestureInProgress () const
addListener()
void addListener (Listener * listener)
Referenced by VideoParameterAutomation::VideoParameterAutomation().
removeListener()
void removeListener (Listener * listener)
Referenced by VideoParameterAutomation::~VideoParameterAutomation().
sendUpdateNotification()
void sendUpdateNotification ()
References ProcessorParameter::getRealValue(), and ProcessorParameter::Listener::valueChanged().
Referenced by ProcessorParameterFloat::setNormalisedValue(), and ProcessorParameterFloat::setRealValue().
The documentation for this class was generated from the following files:
foleys_ProcessorParameter.h
foleys_ProcessorParameter.cpp