foleys_video_engine: OSDComponent Class Reference
OSDComponent Class Reference
#include <OSDComponent.h>
Inherits Component.
Classes
class MouseIdle
Public Member Functions
OSDComponent ()
void paint (juce::Graphics &g) override
void resized () override
void setClip (std::shared_ptr< foleys::AVClip > newClip)
Public Attributes
juce::Slider seekBar { juce::Slider::LinearHorizontal, juce::Slider::NoTextBox }
juce::TextButton camera { TRANS ("Camera") }
juce::TextButton open { TRANS ("Open") }
juce::TextButton play { TRANS ("Play") }
juce::TextButton pause { TRANS ("Pause") }
juce::TextButton stop { TRANS ("Stop") }
juce::TextButton ffwd { TRANS ("FWD") }
Constructor & Destructor Documentation
OSDComponent()
OSDComponent ()
References camera, ffwd, open, pause, play, seekBar, and stop.
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
setClip()
void setClip (std::shared_ptr< foleys::AVClip > newClip)
Referenced by MainContentComponent::openFile().
Member Data Documentation
seekBar
juce::Slider seekBar { juce::Slider::LinearHorizontal, juce::Slider::NoTextBox }
Referenced by MainContentComponent::MainContentComponent(), MainContentComponent::openFile(), OSDComponent(), and MainContentComponent::timecodeChanged().
camera
juce::TextButton camera { TRANS ("Camera") }
Referenced by MainContentComponent::MainContentComponent(), and OSDComponent().
open
juce::TextButton open { TRANS ("Open") }
Referenced by MainContentComponent::MainContentComponent(), and OSDComponent().
play
juce::TextButton play { TRANS ("Play") }
Referenced by MainContentComponent::MainContentComponent(), and OSDComponent().
pause
juce::TextButton pause { TRANS ("Pause") }
Referenced by MainContentComponent::MainContentComponent(), and OSDComponent().
stop
juce::TextButton stop { TRANS ("Stop") }
Referenced by MainContentComponent::MainContentComponent(), and OSDComponent().
ffwd
juce::TextButton ffwd { TRANS ("FWD") }
Referenced by MainContentComponent::MainContentComponent(), and OSDComponent().
The documentation for this class was generated from the following file:
OSDComponent.h