foleys_video_engine: VideoPluginManager Class Reference
VideoPluginManager Class Reference
The VideoPluginManager is used to create VideoProcessor instances to be placed into the image processing pipeline.
#include <foleys_VideoPluginManager.h>
Public Member Functions
VideoPluginManager (VideoEngine &videoEngine)
void registerVideoProcessor (const juce::String &identifierString, std::function< std::unique_ptr< VideoProcessor >()>)
Register a VideoProcessor factory to create a VideoProcessor instance from an identifying string.
std::unique_ptr< VideoProcessor > createVideoPluginInstance (const juce::String &identifierString, juce::String &error) const
Create an instance of a VideoProcessor from an identifying string.
void populatePluginSelection (juce::PopupMenu &menu)
juce::String getPluginDescriptionFromMenuID (int index)
Detailed Description
The VideoPluginManager is used to create VideoProcessor instances to be placed into the image processing pipeline.
Constructor & Destructor Documentation
VideoPluginManager()
VideoPluginManager (VideoEngine & videoEngine)
References ColourCurveVideoProcessor::getPluginName(), and VideoPluginManager::registerVideoProcessor().
Member Function Documentation
registerVideoProcessor()
void registerVideoProcessor (const juce::String & identifierString, std::function< std::unique_ptr< VideoProcessor >()> factory)
Register a VideoProcessor factory to create a VideoProcessor instance from an identifying string.
Referenced by VideoPluginManager::VideoPluginManager().
createVideoPluginInstance()
std::unique_ptr< VideoProcessor > createVideoPluginInstance (const juce::String & identifierString, juce::String & error) const
Create an instance of a VideoProcessor from an identifying string.
Referenced by VideoEngine::createVideoPluginInstance().
populatePluginSelection()
void populatePluginSelection (juce::PopupMenu & menu)
getPluginDescriptionFromMenuID()
juce::String getPluginDescriptionFromMenuID (int index)
The documentation for this class was generated from the following files:
foleys_VideoPluginManager.h
foleys_VideoPluginManager.cpp