foleys_video_engine: AudioFifo Class Reference
AudioFifo Class Reference final
The AudioFifo is a storage, where the AVReader classes will store the stream of audio samples for pre buffering.
#include <foleys_AudioFifo.h>
Public Member Functions
AudioFifo (int size=48000)
void pushSamples (const juce::AudioBuffer< float > &samples)
void pullSamples (const juce::AudioSourceChannelInfo &info)
void pushSilence (int numSamples)
void skipSamples (int numSamples)
void setPosition (const int64_t position)
This method will set the read and write pointer to position, render the fifo empty.
int64_t getWritePosition () const
int64_t getReadPosition () const
int getFreeSpace () const
int getAvailableSamples () const
void setNumChannels (int numChannels)
void setSampleRate (double sampleRate)
void setNumSamples (int samples)
Detailed Description
The AudioFifo is a storage, where the AVReader classes will store the stream of audio samples for pre buffering.
Constructor & Destructor Documentation
AudioFifo()
AudioFifo (int size = 48000)
Member Function Documentation
pushSamples()
void pushSamples (const juce::AudioBuffer< float > & samples)
Referenced by MediaFoundationReader::Pimpl::readNewData().
pullSamples()
void pullSamples (const juce::AudioSourceChannelInfo & info)
Referenced by MovieClip::getNextAudioBlock().
pushSilence()
void pushSilence (int numSamples)
Referenced by MediaFoundationReader::Pimpl::readNewData().
skipSamples()
void skipSamples (int numSamples)
setPosition()
void setPosition (const int64_t position)
This method will set the read and write pointer to position, render the fifo empty.
Referenced by MovieClip::setNextReadPosition(), and MovieClip::setReader().
getWritePosition()
int64_t getWritePosition () const
Referenced by MediaFoundationReader::Pimpl::readNewData().
getReadPosition()
int64_t getReadPosition () const
getFreeSpace()
int getFreeSpace () const
getAvailableSamples()
int getAvailableSamples () const
Referenced by MovieClip::waitForSamplesReady().
setNumChannels()
void setNumChannels (int numChannels)
Referenced by MovieClip::setReader().
setSampleRate()
void setSampleRate (double sampleRate)
Referenced by MovieClip::prepareToPlay(), and MovieClip::setReader().
setNumSamples()
void setNumSamples (int samples)
Referenced by MovieClip::prepareToPlay().
The documentation for this class was generated from the following files:
foleys_AudioFifo.h
foleys_AudioFifo.cpp