foleys_video_engine: VideoComponentWithDropper Class Reference
VideoComponentWithDropper Class Reference
Public Member Functions
VideoComponentWithDropper ()
bool isInterestedInFileDrag (const juce::StringArray &) override
void filesDropped (const juce::StringArray &files, int, int) override
Public Member Functions inherited from SoftwareView
SoftwareView ()
~SoftwareView () override
void setClip (std::shared_ptr< AVClip > clip) override
std::shared_ptr< AVClip > getClip () const override
void paint (juce::Graphics &g) override
void setContinuousRepaint (int hz) override
void timerCallback () override
void timecodeChanged (int64_t count, double seconds) override
Listen to this callback to get notified, when the time code changes.
Public Member Functions inherited from VideoView
VideoView ()=default
virtual ~VideoView ()=default
Public Member Functions inherited from TimeCodeAware::Listener
virtual ~Listener ()=default
Destructor.
Public Attributes
std::function< void(juce::File)> onFileDropped
Constructor & Destructor Documentation
VideoComponentWithDropper()
VideoComponentWithDropper ()
References SoftwareView::setContinuousRepaint().
Member Function Documentation
isInterestedInFileDrag()
bool isInterestedInFileDrag (const juce::StringArray &) override
filesDropped()
void filesDropped (const juce::StringArray & files, int , int) override
References onFileDropped.
Member Data Documentation
onFileDropped
std::function<void (juce::File)> onFileDropped
Referenced by filesDropped(), and MainContentComponent::MainContentComponent().
The documentation for this class was generated from the following file:
VideoPlayer/Source/MainComponent.cpp