foleys_video_engine: MediaFoundationReader Class Reference
MediaFoundationReader Class Reference
#include <foleys_MediaFoundation_Win.h>
Classes
struct Pimpl
Public Member Functions
MediaFoundationReader (const juce::File &file, StreamTypes type)
juce::File getMediaFile () const override
juce::int64 getTotalLength () const override
Returns the length in samples.
double getLengthInSeconds () const override
Returns the length of the clip in seconds.
void setPosition (const int64_t position) override
Seek the reader to a certain position.
juce::Image getStillImage (double seconds, Size size) override
This method allows direct access to a specific time to render thumbnails.
void readNewData (VideoFifo &, AudioFifo &) override
bool hasVideo () const override
bool hasAudio () const override
bool hasSubtitle () const override
void setOutputSampleRate (double sampleRate) override
int getNumVideoStreams () const override
VideoStreamSettings getVideoSettings (int streamIndex) const override
int getNumAudioStreams () const override
AudioStreamSettings getAudioSettings (int streamIndex) const override
Public Member Functions inherited from AVReader
AVReader ()=default
virtual ~AVReader ()=default
bool isOpenedOk () const
Static Public Attributes
static constexpr auto kMaxFramesToTryBeforeTcFound = 40
Additional Inherited Members
Public Attributes inherited from AVReader
Size originalSize
int pixelFormat
double timebase = {}
double sampleRate = {}
int numChannels = 0
juce::int64 numSamples = 0
Protected Attributes inherited from AVReader
bool opened = false
Constructor & Destructor Documentation
MediaFoundationReader()
MediaFoundationReader (const juce::File & file, foleys::StreamTypes type)
Member Function Documentation
getMediaFile()
juce::File getMediaFile () const override virtual
Implements AVReader.
getTotalLength()
juce::int64 getTotalLength () const override virtual
Returns the length in samples.
Note before prepareToPlay this returns the number of samples in the audio stream. Since the Reader will resample to suit the output, this number can change.
Implements AVReader.
getLengthInSeconds()
double getLengthInSeconds () const override virtual
Returns the length of the clip in seconds.
Implements AVReader.
Referenced by MediaFoundationReader::Pimpl::getTotalLength().
setPosition()
void setPosition (const int64_t position) override virtual
Seek the reader to a certain position.
This position is given in audio samples
Implements AVReader.
getStillImage()
juce::Image getStillImage (double seconds, Size size) override virtual
This method allows direct access to a specific time to render thumbnails.
Don't use this to stream the video. Ideally use a separate reader for the thumbnails.
Implements AVReader.
readNewData()
void readNewData (VideoFifo & videoFifo, AudioFifo & audioFifo) override virtual
Implements AVReader.
hasVideo()
bool hasVideo () const override virtual
Implements AVReader.
References MediaFoundationReader::getNumVideoStreams().
hasAudio()
bool hasAudio () const override virtual
Implements AVReader.
References MediaFoundationReader::getNumAudioStreams().
hasSubtitle()
bool hasSubtitle () const override virtual
Implements AVReader.
setOutputSampleRate()
void setOutputSampleRate (double sampleRate) override virtual
Implements AVReader.
References AVReader::sampleRate.
getNumVideoStreams()
int getNumVideoStreams () const override virtual
Implements AVReader.
Referenced by MediaFoundationReader::hasVideo().
getVideoSettings()
VideoStreamSettings getVideoSettings (int streamIndex) const override virtual
Implements AVReader.
getNumAudioStreams()
int getNumAudioStreams () const override virtual
Implements AVReader.
Referenced by MediaFoundationReader::hasAudio().
getAudioSettings()
AudioStreamSettings getAudioSettings (int streamIndex) const override virtual
Implements AVReader.
Member Data Documentation
kMaxFramesToTryBeforeTcFound
constexpr auto kMaxFramesToTryBeforeTcFound = 40 static constexpr
Referenced by MediaFoundationReader::Pimpl::getStillImage().
The documentation for this class was generated from the following files:
foleys_MediaFoundation_Win.h
foleys_MediaFoundation_Win.cpp