foleys_video_engine: AVFormatManager Class Reference
AVFormatManager Class Reference
This class will create the appropriate type of AVClip depending on the supplied file type.
#include <foleys_AVFormatManager.h>
Public Types
enum class Formats { PROBE = 0 , FFmpeg }
Public Member Functions
AVFormatManager ()
std::shared_ptr< AVClip > createClipFromFile (VideoEngine &engine, juce::URL url, StreamTypes type=StreamTypes::all())
std::unique_ptr< AVReader > createReaderFor (juce::File file, StreamTypes type=StreamTypes::all())
std::unique_ptr< AVWriter > createClipWriter (juce::File file)
void registerFormat (std::unique_ptr< AVFormat > format)
void registerFactory (const juce::String &schema, std::function< std::shared_ptr< AVClip >(foleys::VideoEngine &videoEngine, juce::URL url, StreamTypes type)> factory)
Public Attributes
juce::AudioFormatManager audioFormatManager
Detailed Description
This class will create the appropriate type of AVClip depending on the supplied file type.
You don't need to create your own, the VideoEngine has an instance ready, that should be used.
Member Enumeration Documentation
Formats
enum class Formats strong
Enumerator
PROBE
FFmpeg
Constructor & Destructor Documentation
AVFormatManager()
AVFormatManager ()
References AVFormatManager::audioFormatManager.
Member Function Documentation
createClipFromFile()
std::shared_ptr< AVClip > createClipFromFile (VideoEngine & engine, juce::URL url, StreamTypes type = StreamTypes::all())
References AVFormatManager::audioFormatManager, AVFormatManager::createReaderFor(), and StreamTypes::video().
Referenced by VideoEngine::createClipFromFile().
createReaderFor()
std::unique_ptr< AVReader > createReaderFor (juce::File file, StreamTypes type = StreamTypes::all())
Referenced by AVFormatManager::createClipFromFile(), and VideoEngine::createReaderFor().
createClipWriter()
std::unique_ptr< AVWriter > createClipWriter (juce::File file)
Referenced by ClipRenderer::startRendering().
registerFormat()
void registerFormat (std::unique_ptr< AVFormat > format)
Referenced by MainContentComponent::MainContentComponent().
registerFactory()
void registerFactory (const juce::String & schema, std::function< std::shared_ptr< AVClip >(foleys::VideoEngine &videoEngine, juce::URL url, StreamTypes type)> factory)
Member Data Documentation
audioFormatManager
juce::AudioFormatManager audioFormatManager
Referenced by AVFormatManager::AVFormatManager(), AVFormatManager::createClipFromFile(), and VideoEngine::getAudioFormatManager().
The documentation for this class was generated from the following files:
foleys_AVFormatManager.h
foleys_AVFormatManager.cpp