foleys_video_engine: ProcessorState Class Reference
ProcessorState Class Reference
The ProcessorState is a convenient class to manage your ProcessorParameters in a VideoProcessor.
#include <foleys_ProcessorParameter.h>
Public Member Functions
ProcessorState (void *, juce::UndoManager *, const juce::String &rootType, ParameterMap layout)
ProcessorParameter * getParameter (const juce::Identifier &paramID)
double * getRawParameterValue (const juce::Identifier &paramID)
std::vector< ProcessorParameter * > getParameters ()
Public Attributes
juce::ValueTree state
Detailed Description
The ProcessorState is a convenient class to manage your ProcessorParameters in a VideoProcessor.
Constructor & Destructor Documentation
ProcessorState()
ProcessorState (void * , juce::UndoManager * undo, const juce::String & rootType, ParameterMap layout)
Member Function Documentation
getParameter()
ProcessorParameter * getParameter (const juce::Identifier & paramID)
Referenced by ProcessorState::getRawParameterValue().
getRawParameterValue()
double * getRawParameterValue (const juce::Identifier & paramID)
References ProcessorState::getParameter().
Referenced by ColourCurveVideoProcessor::ColourCurveVideoProcessor().
getParameters()
std::vector< ProcessorParameter * > getParameters ()
Referenced by ColourCurveVideoProcessor::getParameters().
Member Data Documentation
state
juce::ValueTree state
Referenced by ColourCurveVideoProcessor::getStateInformation(), and ColourCurveVideoProcessor::setStateInformation().
The documentation for this class was generated from the following files:
foleys_ProcessorParameter.h
foleys_ProcessorParameter.cpp