foleys_video_engine: LevelMeterLookAndFeelMethods.h File Reference
LevelMeterLookAndFeelMethods.h File Reference
Functions
void setupDefaultMeterColours () override
void updateMeterGradients () override
juce::Rectangle< float > getMeterInnerBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
juce::Rectangle< float > getMeterBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType, int numChannels, int channel) const override
juce::Rectangle< float > getMeterBarBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the actual meter bar.
juce::Rectangle< float > getMeterTickmarksBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the tickmarks.
juce::Rectangle< float > getMeterClipIndicatorBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the clip indicator light.
juce::Rectangle< float > getMeterMaxNumberBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the max level.
juce::Rectangle< float > drawBackground (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
void drawMeterBars (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, const foleys::LevelMeterSource *source, int fixedNumChannels=-1, int selectedChannel=-1) override
void drawMeterBarsBackground (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, int numChannels, int fixedNumChannels) override
void drawMeterChannel (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, const foleys::LevelMeterSource *source, int selectedChannel) override
void drawMeterChannelBackground (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
void drawMeterBar (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, float rms, float peak) override
void drawMeterReduction (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, float reduction) override
void drawMeterBarBackground (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
void drawTickMarks (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
void drawClipIndicator (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, bool hasClipped) override
void drawClipIndicatorBackground (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
void drawMaxNumber (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, float maxGain) override
void drawMaxNumberBackground (juce::Graphics &g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
int hitTestClipIndicator (juce::Point< int > position, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, const foleys::LevelMeterSource *source) const override
int hitTestMaxNumber (juce::Point< int > position, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, const foleys::LevelMeterSource *source) const override
Function Documentation
setupDefaultMeterColours()
void setupDefaultMeterColours () override
References LevelMeter::lmBackgroundClipColour, LevelMeter::lmBackgroundColour, LevelMeter::lmMeterBackgroundColour, LevelMeter::lmMeterForegroundColour, LevelMeter::lmMeterGradientLowColour, LevelMeter::lmMeterGradientMaxColour, LevelMeter::lmMeterGradientMidColour, LevelMeter::lmMeterMaxNormalColour, LevelMeter::lmMeterMaxOverColour, LevelMeter::lmMeterMaxWarnColour, LevelMeter::lmMeterOutlineColour, LevelMeter::lmMeterReductionColour, LevelMeter::lmOutlineColour, LevelMeter::lmTextClipColour, LevelMeter::lmTextColour, LevelMeter::lmTextDeactiveColour, and LevelMeter::lmTicksColour.
updateMeterGradients()
void updateMeterGradients () override
getMeterInnerBounds()
juce::Rectangle< float > getMeterInnerBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
References LevelMeter::HasBorder.
Referenced by drawMeterBars(), and drawMeterBarsBackground().
getMeterBounds()
juce::Rectangle< float > getMeterBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType, int numChannels, int channel) const override
References LevelMeter::Horizontal, and LevelMeter::SingleChannel.
Referenced by drawMeterBars(), drawMeterBarsBackground(), hitTestClipIndicator(), and hitTestMaxNumber().
getMeterBarBounds()
juce::Rectangle< float > getMeterBarBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the actual meter bar.
References LevelMeter::Horizontal, LevelMeter::MaxNumber, LevelMeter::Minimal, and LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterBarsBackground(), drawMeterChannel(), drawMeterChannelBackground(), and getMeterTickmarksBounds().
getMeterTickmarksBounds()
juce::Rectangle< float > getMeterTickmarksBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the tickmarks.
To disable this feature return an empty rectangle.
References getMeterBarBounds(), LevelMeter::Horizontal, LevelMeter::Minimal, and LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterBarsBackground(), and drawMeterChannelBackground().
getMeterClipIndicatorBounds()
juce::Rectangle< float > getMeterClipIndicatorBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the clip indicator light.
To disable this feature return an empty rectangle.
References LevelMeter::Horizontal, LevelMeter::Minimal, and LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterBarsBackground(), drawMeterChannel(), drawMeterChannelBackground(), and hitTestClipIndicator().
getMeterMaxNumberBounds()
juce::Rectangle< float > getMeterMaxNumberBounds (juce::Rectangle< float > bounds, foleys::LevelMeter::MeterFlags meterType) const override
Override this callback to define the placement of the max level.
To disable this feature return an empty rectangle.
References LevelMeter::Horizontal, LevelMeter::MaxNumber, LevelMeter::Minimal, and LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterChannel(), drawMeterChannelBackground(), and hitTestMaxNumber().
drawBackground()
juce::Rectangle< float > drawBackground (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
References LevelMeter::HasBorder, LevelMeter::lmBackgroundColour, and LevelMeter::lmOutlineColour.
drawMeterBars()
void drawMeterBars (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, const foleys::LevelMeterSource * source, int fixedNumChannels = -1, int selectedChannel = -1) override
References drawClipIndicator(), drawMaxNumber(), drawMeterBar(), drawMeterChannel(), drawMeterReduction(), drawTickMarks(), LevelMeterSource::getClipFlag(), LevelMeterSource::getMaxLevel(), LevelMeterSource::getMaxOverallLevel(), getMeterBarBounds(), getMeterBounds(), getMeterClipIndicatorBounds(), getMeterInnerBounds(), getMeterMaxNumberBounds(), getMeterTickmarksBounds(), LevelMeterSource::getNumChannels(), LevelMeterSource::getReductionLevel(), LevelMeterSource::getRMSLevel(), LevelMeter::Horizontal, LevelMeter::Minimal, and LevelMeter::SingleChannel.
drawMeterBarsBackground()
void drawMeterBarsBackground (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, int numChannels, int fixedNumChannels) override
References drawClipIndicatorBackground(), drawMeterBarBackground(), drawMeterChannelBackground(), drawTickMarks(), getMeterBarBounds(), getMeterBounds(), getMeterClipIndicatorBounds(), getMeterInnerBounds(), getMeterTickmarksBounds(), LevelMeter::Horizontal, LevelMeter::Minimal, and LevelMeter::SingleChannel.
drawMeterChannel()
void drawMeterChannel (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, const foleys::LevelMeterSource * source, int selectedChannel) override
References drawClipIndicator(), drawMaxNumber(), drawMeterBar(), drawMeterReduction(), LevelMeterSource::getClipFlag(), LevelMeterSource::getMaxLevel(), LevelMeterSource::getMaxOverallLevel(), getMeterBarBounds(), getMeterClipIndicatorBounds(), getMeterMaxNumberBounds(), LevelMeterSource::getReductionLevel(), LevelMeterSource::getRMSLevel(), LevelMeter::Horizontal, and LevelMeter::Reduction.
Referenced by drawMeterBars().
drawMeterChannelBackground()
void drawMeterChannelBackground (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
References drawClipIndicatorBackground(), drawMaxNumberBackground(), drawMeterBarBackground(), drawTickMarks(), getMeterBarBounds(), getMeterClipIndicatorBounds(), getMeterMaxNumberBounds(), and getMeterTickmarksBounds().
Referenced by drawMeterBarsBackground().
drawMeterBar()
void drawMeterBar (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, float rms, float peak) override
References LevelMeter::Horizontal, LevelMeter::lmMeterGradientLowColour, LevelMeter::lmMeterGradientMaxColour, LevelMeter::lmMeterGradientMidColour, LevelMeter::lmMeterMaxNormalColour, LevelMeter::lmMeterMaxOverColour, LevelMeter::lmMeterMaxWarnColour, LevelMeter::lmMeterReductionColour, LevelMeter::Reduction, and LevelMeter::Vintage.
Referenced by drawMeterBars(), and drawMeterChannel().
drawMeterReduction()
void drawMeterReduction (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, float reduction) override
References LevelMeter::Horizontal, and LevelMeter::lmMeterReductionColour.
Referenced by drawMeterBars(), and drawMeterChannel().
drawMeterBarBackground()
void drawMeterBarBackground (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
References LevelMeter::lmMeterBackgroundColour, and LevelMeter::lmMeterOutlineColour.
Referenced by drawMeterBarsBackground(), and drawMeterChannelBackground().
drawTickMarks()
void drawTickMarks (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
References LevelMeter::Horizontal, LevelMeter::lmTicksColour, LevelMeter::Minimal, LevelMeter::Reduction, and LevelMeter::Vintage.
Referenced by drawMeterBars(), drawMeterBarsBackground(), and drawMeterChannelBackground().
drawClipIndicator()
void drawClipIndicator (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, bool hasClipped) override
References LevelMeter::lmBackgroundClipColour, LevelMeter::lmMeterBackgroundColour, and LevelMeter::lmMeterOutlineColour.
Referenced by drawMeterBars(), and drawMeterChannel().
drawClipIndicatorBackground()
void drawClipIndicatorBackground (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
References LevelMeter::lmMeterBackgroundColour, and LevelMeter::lmMeterOutlineColour.
Referenced by drawMeterBarsBackground(), and drawMeterChannelBackground().
drawMaxNumber()
void drawMaxNumber (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, float maxGain) override
References LevelMeter::lmMeterBackgroundColour, LevelMeter::lmMeterOutlineColour, LevelMeter::lmTextClipColour, and LevelMeter::lmTextColour.
Referenced by drawMeterBars(), and drawMeterChannel().
drawMaxNumberBackground()
void drawMaxNumberBackground (juce::Graphics & g, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds) override
References LevelMeter::lmMeterBackgroundColour.
Referenced by drawMeterChannelBackground().
hitTestClipIndicator()
int hitTestClipIndicator (juce::Point< int > position, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, const foleys::LevelMeterSource * source) const override
References getMeterBounds(), getMeterClipIndicatorBounds(), and LevelMeterSource::getNumChannels().
hitTestMaxNumber()
int hitTestMaxNumber (juce::Point< int > position, foleys::LevelMeter::MeterFlags meterType, juce::Rectangle< float > bounds, const foleys::LevelMeterSource * source) const override
References getMeterBounds(), getMeterMaxNumberBounds(), and LevelMeterSource::getNumChannels().