foleys_video_engine: microsoft_utils.cpp File Reference
microsoft_utils.cpp File Reference
Functions
HRESULT CopyAttribute (IMFAttributes *pSrc, IMFAttributes *pDest, const GUID &key)
HRESULT CloneVideoMediaType (IMFMediaType *pSrcMediaType, REFGUID guidSubType, IMFMediaType **ppNewMediaType)
HRESULT CreatePhotoMediaType (IMFMediaType *pSrcMediaType, IMFMediaType **ppPhotoMediaType)
Function Documentation
CopyAttribute()
HRESULT CopyAttribute (IMFAttributes * pSrc, IMFAttributes * pDest, const GUID & key)
Referenced by CloneVideoMediaType(), and CreatePhotoMediaType().
CloneVideoMediaType()
HRESULT CloneVideoMediaType (IMFMediaType * pSrcMediaType, REFGUID guidSubType, IMFMediaType ** ppNewMediaType)
References CopyAttribute(), MFScopedPointer< T >::get(), and MFScopedPointer< T >::getPointer().
CreatePhotoMediaType()
HRESULT CreatePhotoMediaType (IMFMediaType * pSrcMediaType, IMFMediaType ** ppPhotoMediaType)
References CopyAttribute(), MFScopedPointer< T >::get(), and MFScopedPointer< T >::getPointer().