foleys_video_engine: Pimpl Struct Reference
Pimpl Struct Reference
Classes
class CaptureEngineCB
struct SampleCallback
Public Member Functions
Pimpl (CameraReceiver &ownerToUse, int index, void *session)
Pimpl (CameraReceiver &ownerToUse, const juce::String &uid, void *session)
~Pimpl ()
juce::String getCameraName () const
juce::String getCameraUid () const
bool isReady () const
bool start ()
bool stop ()
juce::Array< CameraReceiver::Resolution > getAvailableResolutions ()
bool setResolution (int)
void setResolutionIndex (int index)
VideoFrame & getNewFrameToFill ()
void finishWriting ()
Constructor & Destructor Documentation
Pimpl() [1/2]
Pimpl (CameraReceiver & ownerToUse, int index, void * session)
References Pimpl::getCameraDevice().
Pimpl() [2/2]
Pimpl (CameraReceiver & ownerToUse, const juce::String & uid, void * session)
References Pimpl::getCameraDevice().
~Pimpl()
~Pimpl ()
Member Function Documentation
getCameraName()
juce::String getCameraName () const
getCameraUid()
juce::String getCameraUid () const
isReady()
bool isReady () const
start()
bool start ()
stop()
bool stop ()
getAvailableResolutions()
juce::Array< CameraReceiver::Resolution > getAvailableResolutions ()
References MFScopedPointer< T >::get(), and MFScopedPointer< T >::getPointer().
setResolution()
bool setResolution (int)
setResolutionIndex()
void setResolutionIndex (int index)
References MFScopedPointer< T >::get(), and MFScopedPointer< T >::getPointer().
getNewFrameToFill()
VideoFrame & getNewFrameToFill ()
References VideoFrame::timecode.
finishWriting()
void finishWriting ()
The documentation for this struct was generated from the following file:
foleys_CameraManager_Win.cpp