foleys_video_engine: MediaFoundationReader::Pimpl Struct Reference
MediaFoundationReader::Pimpl Struct Reference
Public Member Functions
Pimpl (MediaFoundationReader &myOwner, const juce::File &file, StreamTypes type)
~Pimpl ()
void setPosition (juce::int64 pos)
double getLengthInSeconds ()
juce::int64 getTotalLength ()
int getNumVideoStreams () const noexcept
int getNumAudioStreams () const noexcept
VideoStreamSettings getVideoSettings (int streamIndex) const noexcept
AudioStreamSettings getAudioSettings (int streamIndex) const noexcept
juce::Image getStillImage (double seconds, Size size)
void readNewData (VideoFifo &, AudioFifo &)
void setOutputSampleRate (double sr)
Constructor & Destructor Documentation
Pimpl()
Pimpl (MediaFoundationReader & myOwner, const juce::File & file, StreamTypes type)
References MFScopedPointer< T >::get(), MFScopedPointer< T >::getPointer(), and AVReader::opened.
~Pimpl()
~Pimpl ()
Member Function Documentation
setPosition()
void setPosition (juce::int64 pos)
getLengthInSeconds()
double getLengthInSeconds ()
getTotalLength()
juce::int64 getTotalLength ()
References MediaFoundationReader::getLengthInSeconds().
getNumVideoStreams()
int getNumVideoStreams () const noexcept
getNumAudioStreams()
int getNumAudioStreams () const noexcept
getVideoSettings()
VideoStreamSettings getVideoSettings (int streamIndex) const noexcept
getAudioSettings()
AudioStreamSettings getAudioSettings (int streamIndex) const noexcept
getStillImage()
juce::Image getStillImage (double seconds, foleys::Size size)
References MFScopedPointer< T >::get(), MFScopedPointer< T >::getPointer(), Size::isEmpty(), MediaFoundationReader::kMaxFramesToTryBeforeTcFound, foleys::LetterBox, and MFScopedPointer< T >::reset().
readNewData()
void readNewData (VideoFifo & videoFifo, AudioFifo & audioFifo)
References VideoFifo::finishWriting(), MFScopedPointer< T >::get(), MFScopedPointer< T >::getPointer(), AudioFifo::getWritePosition(), VideoFifo::getWritingFrame(), AudioFifo::pushSamples(), and AudioFifo::pushSilence().
setOutputSampleRate()
void setOutputSampleRate (double sr)
The documentation for this struct was generated from the following file:
foleys_MediaFoundation_Win.cpp