foleys_video_engine: foleys::MovieClip Class Reference
foleys::MovieClip Class Reference
The MovieClip plays back a video file.
Public Member Functions
MovieClip (VideoEngine &videoEngine)
virtual ~MovieClip ()=default
juce::String getDescription () const override
returns a string describing the clip.
bool openFromFile (const juce::File file)
juce::File getMediaFile () const override
returns the original media file to restore
void setReader (std::unique_ptr< AVReader > reader)
void setThumbnailReader (std::unique_ptr< AVReader > reader)
Size getVideoSize () const override
returns the pixel size of the media as a tuple.
double getLengthInSeconds () const override
Returns the length of the clip in seconds.
double getCurrentTimeInSeconds () const override
Return the clip's read position in seconds.
std::pair< int64_t, juce::Image > getFrame (double pts) const override
Returns the frame for a certain timecode.
bool isFrameAvailable (double pts) const override
Checks, if a frame is available.
juce::Image getCurrentFrame () const override
Returns the frame for the current time.
void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
void releaseResources () override
void getNextAudioBlock (const juce::AudioSourceChannelInfo &) override
void setNextReadPosition (juce::int64 samples) override
juce::int64 getNextReadPosition () const override
juce::int64 getTotalLength () const override
bool isLooping () const override
void setLooping (bool shouldLoop) override
juce::Image getStillImage (double seconds, Size size) override
This returns a still frame on the selected position.
juce::TimeSliceClient * getBackgroundJob () override
bool hasVideo () const override
Returns true, if this clip will produce visual frames.
bool hasAudio () const override
Returns true, if this clip will produce audio.
std::shared_ptr< AVClip > createCopy () override
This returns a copy of the clip.
double getSampleRate () const override
This is the samplerate supplied from prepareToPlay and the sample rate this clip will produce audio and use as clock source.
Public Member Functions inherited from foleys::AVClip
AVClip (VideoEngine &videoEngine)
virtual ~AVClip ()=default
void addTimecodeListener (TimecodeListener *listener)
Register a TimecodeListener to be notified, when the visual frame changes.
void removeTimecodeListener (TimecodeListener *listener)
Unregister a TimecodeListener.
VideoEngine * getVideoEngine () const
Additional Inherited Members
Protected Member Functions inherited from foleys::AVClip
void sendTimecode (int64_t count, double seconds, juce::NotificationType nt)
Subclasses can call this to notify displays, that the time code has changed, e.g.
Detailed Description
The MovieClip plays back a video file.
It buffers an amount of audio and video frames ahead of time. To check, you can call isFrameAvailable(), in case you need to wait for the frame, e.g. for offline bouncing.
Constructor & Destructor Documentation
MovieClip()
foleys::MovieClip::MovieClip (VideoEngine & videoEngine)
~MovieClip()
virtual foleys::MovieClip::~MovieClip () virtual default
Member Function Documentation
getDescription()
juce::String foleys::MovieClip::getDescription () const override virtual
returns a string describing the clip.
This could be the filename of the original media file
Implements foleys::AVClip.
openFromFile()
bool foleys::MovieClip::openFromFile (const juce::File file)
References foleys::AVClip::getVideoEngine(), setReader(), setThumbnailReader(), and foleys::StreamTypes::video().
getMediaFile()
juce::File foleys::MovieClip::getMediaFile () const override virtual
returns the original media file to restore
Reimplemented from foleys::AVClip.
Referenced by createCopy().
setReader()
void foleys::MovieClip::setReader (std::unique_ptr< AVReader > reader)
References foleys::VideoFifo::clear(), foleys::VideoFifo::getVideoSettings(), foleys::AudioFifo::setNumChannels(), foleys::AudioFifo::setPosition(), foleys::AudioFifo::setSampleRate(), and foleys::VideoStreamSettings::timebase.
Referenced by openFromFile().
setThumbnailReader()
void foleys::MovieClip::setThumbnailReader (std::unique_ptr< AVReader > reader)
Referenced by openFromFile().
getVideoSize()
Size foleys::MovieClip::getVideoSize () const override virtual
returns the pixel size of the media as a tuple.
In some video files this can change at any frame.
Implements foleys::AVClip.
getLengthInSeconds()
double foleys::MovieClip::getLengthInSeconds () const override virtual
Returns the length of the clip in seconds.
Implements foleys::AVClip.
getCurrentTimeInSeconds()
double foleys::MovieClip::getCurrentTimeInSeconds () const override virtual
Return the clip's read position in seconds.
Implements foleys::AVClip.
getFrame()
std::pair< int64_t, juce::Image > foleys::MovieClip::getFrame (double pts) const override virtual
Returns the frame for a certain timecode.
Implements foleys::AVClip.
References foleys::VideoFifo::getVideoFrame().
isFrameAvailable()
bool foleys::MovieClip::isFrameAvailable (double pts) const override virtual
Checks, if a frame is available.
Implements foleys::AVClip.
References foleys::VideoFifo::isFrameAvailable().
getCurrentFrame()
juce::Image foleys::MovieClip::getCurrentFrame () const override virtual
Returns the frame for the current time.
Implements foleys::AVClip.
References foleys::AudioFifo::getReadPosition(), and foleys::VideoFifo::getVideoFrame().
prepareToPlay()
void foleys::MovieClip::prepareToPlay (int samplesPerBlockExpected, double sampleRate) override
References foleys::AudioFifo::setNumSamples(), and foleys::AudioFifo::setSampleRate().
releaseResources()
void foleys::MovieClip::releaseResources () override
getNextAudioBlock()
void foleys::MovieClip::getNextAudioBlock (const juce::AudioSourceChannelInfo & info) override
References foleys::AudioFifo::pullSamples().
setNextReadPosition()
void foleys::MovieClip::setNextReadPosition (juce::int64 samples) override
References foleys::AudioFifo::setPosition().
getNextReadPosition()
juce::int64 foleys::MovieClip::getNextReadPosition () const override
getTotalLength()
juce::int64 foleys::MovieClip::getTotalLength () const override
isLooping()
bool foleys::MovieClip::isLooping () const override
setLooping()
void foleys::MovieClip::setLooping (bool shouldLoop) override
getStillImage()
juce::Image foleys::MovieClip::getStillImage (double seconds, Size size) override virtual
This returns a still frame on the selected position.
Don't use this method for streaming a video, because it will be slow
Implements foleys::AVClip.
getBackgroundJob()
juce::TimeSliceClient * foleys::MovieClip::getBackgroundJob () override virtual
Reimplemented from foleys::AVClip.
hasVideo()
bool foleys::MovieClip::hasVideo () const override virtual
Returns true, if this clip will produce visual frames.
Implements foleys::AVClip.
Referenced by getSampleRate().
hasAudio()
bool foleys::MovieClip::hasAudio () const override virtual
Returns true, if this clip will produce audio.
Implements foleys::AVClip.
createCopy()
std::shared_ptr< AVClip > foleys::MovieClip::createCopy () override virtual
This returns a copy of the clip.
Note that this will not work properly if the clip is not properly registered in the engine, because the copy will automatically be registered with the engine as well.
Implements foleys::AVClip.
References getMediaFile(), and foleys::AVClip::getVideoEngine().
getSampleRate()
double foleys::MovieClip::getSampleRate () const override virtual
This is the samplerate supplied from prepareToPlay and the sample rate this clip will produce audio and use as clock source.
Implements foleys::AVClip.
References foleys::VideoFifo::clearFramesOlderThan(), foleys::VideoFifo::getFrameCountForTime(), hasVideo(), and foleys::AVClip::sendTimecode().
The documentation for this class was generated from the following files:
MovieClip.h
MovieClip.cpp