foleys_video_engine: foleys::PositioningVideoProcessor Class Reference
foleys::PositioningVideoProcessor Class Reference
Public Member Functions
std::vector< std::unique_ptr< ProcessorParameter > > createParameters ()
const juce::String getName () const override
Override this method to return a human readable name to identify the processor later.
PositioningVideoProcessor ()
void processFrameReplacing (juce::Image &frame, int64_t count, const VideoStreamSettings &settings, double clipDuration) override
Override this method to implement the actual video processing.
void processFrame (juce::Image &output, const juce::Image &input, int64_t count, const VideoStreamSettings &settings, double clipDuration) override
Override this method to implement the actual video processing.
std::vector< ProcessorParameter * > getParameters () override
Public Member Functions inherited from foleys::VideoProcessor
VideoProcessor ()=default
virtual ~VideoProcessor ()=default
Static Public Member Functions
static juce::String getPluginName ()
Constructor & Destructor Documentation
PositioningVideoProcessor()
foleys::PositioningVideoProcessor::PositioningVideoProcessor ()
References foleys::ProcessorState::getRawParameterValue().
Member Function Documentation
getPluginName()
static juce::String foleys::PositioningVideoProcessor::getPluginName () static
Referenced by getName(), and foleys::VideoPluginManager::VideoPluginManager().
createParameters()
std::vector<std::unique_ptr<ProcessorParameter> > foleys::PositioningVideoProcessor::createParameters ()
getName()
const juce::String foleys::PositioningVideoProcessor::getName () const override virtual
Override this method to return a human readable name to identify the processor later.
Implements foleys::VideoProcessor.
References getPluginName().
processFrameReplacing()
void foleys::PositioningVideoProcessor::processFrameReplacing (juce::Image & frame, int64_t count, const VideoStreamSettings & settings, double clipDuration) override virtual
Override this method to implement the actual video processing.
Parameters
frame this is the image of the frame
count this is the frame counter in settings.timebase counts
settings is the output settings that you will produce. You find the size and the timebase here
clipDuration is the duration of the clip. This is especially handy for creating transitions
Implements foleys::VideoProcessor.
References processFrame().
processFrame()
void foleys::PositioningVideoProcessor::processFrame (juce::Image & output, const juce::Image & input, int64_t count, const VideoStreamSettings & settings, double clipDuration) override virtual
Override this method to implement the actual video processing.
The default implementation creates a copy and calls processFrameReplacing. But for some processors you might want to save the copy step for performance reasons.
Parameters
output is the image to write into
input is the original image to read from
count this is the frame counter in settings.timebase counts
settings is the output settings that you will produce. You find the size and the timebase here
clipDuration is the duration of the clip. This is especially handy for creating transitions
Reimplemented from foleys::VideoProcessor.
References foleys::VideoStreamSettings::frameSize, foleys::Size::height, and foleys::Size::width.
Referenced by processFrameReplacing().
getParameters()
std::vector<ProcessorParameter*> foleys::PositioningVideoProcessor::getParameters () override virtual
Implements foleys::VideoProcessor.
References foleys::ProcessorState::getParameters().
The documentation for this class was generated from the following file:
PositioningVideoProcessor.h