foleys_video_engine: ClipRenderer Class Reference
ClipRenderer Class Reference
Public Member Functions
ClipRenderer (VideoEngine &engine)
void setOutputFile (juce::File file)
juce::File getOutputFile () const
void setClipToRender (std::shared_ptr< AVClip > clip)
void setVideoSettings (const VideoStreamSettings &settings)
void setAudioSettings (const AudioStreamSettings &settings)
void startRendering (bool cancelRunningJob)
void cancelRendering ()
bool isRendering () const
Public Attributes
std::function< void(bool success)> onRenderingFinished
std::atomic< double > progress {}
Constructor & Destructor Documentation
ClipRenderer()
ClipRenderer (VideoEngine & engine)
Member Function Documentation
setOutputFile()
void setOutputFile (juce::File file)
getOutputFile()
juce::File getOutputFile () const
setClipToRender()
void setClipToRender (std::shared_ptr< AVClip > clip)
setVideoSettings()
void setVideoSettings (const VideoStreamSettings & settings)
setAudioSettings()
void setAudioSettings (const AudioStreamSettings & settings)
startRendering()
void startRendering (bool cancelRunningJob)
References AVFormatManager::createClipWriter(), AudioStreamSettings::defaultNumSamples, VideoEngine::getFormatManager(), VideoEngine::getThreadPool(), ClipRenderer::progress, and AudioStreamSettings::timebase.
cancelRendering()
void cancelRendering ()
References VideoEngine::getThreadPool(), and ClipRenderer::onRenderingFinished.
isRendering()
bool isRendering () const
Member Data Documentation
onRenderingFinished
std::function<void(bool success)> onRenderingFinished
Referenced by ClipRenderer::cancelRendering().
progress
std::atomic<double> progress {}
Referenced by ClipRenderer::startRendering().
The documentation for this class was generated from the following files:
ClipRenderer.h
ClipRenderer.cpp