foleys_video_engine: VideoEngine Class Reference
VideoEngine Class Reference
The VideoEngine is handling the background tasks of the video.
Public Member Functions
VideoEngine ()
~VideoEngine ()
std::shared_ptr< AVClip > createClipFromFile (juce::File file)
std::shared_ptr< ComposedClip > createComposedClip ()
std::unique_ptr< AVReader > createReaderFor (juce::File file, StreamTypes type=StreamTypes::all())
void addJob (std::function< void()> job)
void addJob (juce::ThreadPoolJob *job, bool deleteJobWhenFinished)
void cancelJob (juce::ThreadPoolJob *job)
juce::ThreadPool & getThreadPool ()
void manageLifeTime (std::shared_ptr< AVClip > clip)
This method will add the clip to the background threads and hold an auto release pool to make sure, it won't be deleted in any realtime critical thread.
void setUndoManager (juce::UndoManager *undoManager)
You can set an external undomanager.
juce::UndoManager * getUndoManager ()
AVFormatManager & getFormatManager ()
std::unique_ptr< VideoProcessor > createVideoPluginInstance (const juce::String &identifierString, juce::String &error) const
std::unique_ptr< juce::AudioProcessor > createAudioPluginInstance (const juce::String &identifierString, double sampleRate, int blockSize, juce::String &error) const
juce::TimeSliceThread & getNextTimeSliceThread ()
Detailed Description
The VideoEngine is handling the background tasks of the video.
You should have only one instance.
You can use the VideoEngine to create instances of AVClip, using the built in AVFormatManager. It also manages the lifetime of the clips, managing the auto release pool and the thread pools for reading ahead and for creating the thumbnails.
Constructor & Destructor Documentation
VideoEngine()
VideoEngine ()
~VideoEngine()
~VideoEngine ()
Member Function Documentation
createClipFromFile()
std::shared_ptr< AVClip > createClipFromFile (juce::File file)
createComposedClip()
std::shared_ptr< ComposedClip > createComposedClip ()
createReaderFor()
std::unique_ptr< AVReader > createReaderFor (juce::File file, StreamTypes type = StreamTypes::all())
References AVFormatManager::createReaderFor().
addJob() [1/2]
void addJob (std::function< void()> job)
addJob() [2/2]
void addJob (juce::ThreadPoolJob * job, bool deleteJobWhenFinished)
cancelJob()
void cancelJob (juce::ThreadPoolJob * job)
getThreadPool()
juce::ThreadPool & getThreadPool ()
Referenced by ClipBouncer::cancelRendering(), and ClipBouncer::startRendering().
manageLifeTime()
void manageLifeTime (std::shared_ptr< AVClip > clip)
This method will add the clip to the background threads and hold an auto release pool to make sure, it won't be deleted in any realtime critical thread.
setUndoManager()
void setUndoManager (juce::UndoManager * undoManager)
You can set an external undomanager.
In this case you are responsible for detetion. If you use the undomanager provided by the engine, you don't have to do anything for it's lifetime.
getUndoManager()
juce::UndoManager * getUndoManager ()
getFormatManager()
AVFormatManager & getFormatManager ()
Referenced by ClipBouncer::startRendering().
createVideoPluginInstance()
std::unique_ptr< VideoProcessor > createVideoPluginInstance (const juce::String & identifierString, juce::String & error) const
References VideoPluginManager::createVideoPluginInstance().
createAudioPluginInstance()
std::unique_ptr< juce::AudioProcessor > createAudioPluginInstance (const juce::String & identifierString, double sampleRate, int blockSize, juce::String & error) const
References AudioPluginManager::createAudioPluginInstance().
getNextTimeSliceThread()
juce::TimeSliceThread & getNextTimeSliceThread ()
Referenced by AudioClip::setAudioFormatReader().
The documentation for this class was generated from the following files:
VideoEngine.h
VideoEngine.cpp