foleys_video_engine: foleys::ProcessorParameter::Listener Class Reference
foleys::ProcessorParameter::Listener Class Reference abstract
Public Member Functions
Listener ()=default
virtual ~Listener ()=default
virtual void valueChanged (double newValue)=0
virtual void gestureStarted ()=0
virtual void gestureFinished ()=0
Constructor & Destructor Documentation
Listener()
foleys::ProcessorParameter::Listener::Listener () default
~Listener()
virtual foleys::ProcessorParameter::Listener::~Listener () virtual default
Member Function Documentation
valueChanged()
virtual void foleys::ProcessorParameter::Listener::valueChanged (double newValue) pure virtual
Implemented in foleys::VideoParameterAutomation.
Referenced by foleys::ProcessorParameter::sendUpdateNotification().
gestureStarted()
virtual void foleys::ProcessorParameter::Listener::gestureStarted () pure virtual
Implemented in foleys::VideoParameterAutomation.
Referenced by foleys::ProcessorParameter::beginGesture().
gestureFinished()
virtual void foleys::ProcessorParameter::Listener::gestureFinished () pure virtual
Implemented in foleys::VideoParameterAutomation.
Referenced by foleys::ProcessorParameter::endGesture().
The documentation for this class was generated from the following file:
ProcessorParameter.h