foleys_video_engine: AudioPluginManager Class Reference
AudioPluginManager Class Reference
The AudioPluginManager is used to create AudioProcessor instances to be placed into the audio processing pipeline.
Public Member Functions
AudioPluginManager (VideoEngine &videoEngine)
void registerAudioProcessor (const juce::String &identifierString, std::function< std::unique_ptr< juce::AudioProcessor >()>)
Register a factory to return an AudioProcessor instance from an identifierString.
std::unique_ptr< juce::AudioProcessor > createAudioPluginInstance (const juce::String &identifierString, double sampleRate, int blockSize, juce::String &error) const
Creates an actual instance of an AudioPlugin.
juce::Array< juce::PluginDescription > getKnownPluginDescriptions () const
void setPluginDataFile (const juce::File &file)
Set a file to save the results of plugin scanning to.
Detailed Description
The AudioPluginManager is used to create AudioProcessor instances to be placed into the audio processing pipeline.
You can add support for 3rd party plugins here.
Constructor & Destructor Documentation
AudioPluginManager()
AudioPluginManager (VideoEngine & videoEngine)
References PanningAudioProcessor::getPluginName(), and AudioPluginManager::registerAudioProcessor().
Member Function Documentation
registerAudioProcessor()
void registerAudioProcessor (const juce::String & identifierString, std::function< std::unique_ptr< juce::AudioProcessor >()> factory)
Register a factory to return an AudioProcessor instance from an identifierString.
This is used for built in AudioProcessors.
Referenced by AudioPluginManager::AudioPluginManager().
createAudioPluginInstance()
std::unique_ptr< juce::AudioProcessor > createAudioPluginInstance (const juce::String & identifierString, double sampleRate, int blockSize, juce::String & error) const
Creates an actual instance of an AudioPlugin.
It will try the first the built in factories, and then the AudioPlugins that were found on the system.
Referenced by VideoEngine::createAudioPluginInstance().
getKnownPluginDescriptions()
juce::Array< juce::PluginDescription > getKnownPluginDescriptions () const
setPluginDataFile()
void setPluginDataFile (const juce::File & file)
Set a file to save the results of plugin scanning to.
It will read first, if the file exists. On success, it writes the plugin database to the file.
References VideoEngine::addJob().
The documentation for this class was generated from the following files:
foleys_AudioPluginManager.h
foleys_AudioPluginManager.cpp