foleys_video_engine: foleys::ClipBouncer Class Reference
foleys::ClipBouncer Class Reference
Public Member Functions
ClipBouncer (VideoEngine &engine)
void setOutputFile (juce::File file)
juce::File getOutputFile () const
void setClipToRender (std::shared_ptr< AVClip > clip)
void setVideoSettings (const VideoStreamSettings &settings)
void setAudioSettings (const AudioStreamSettings &settings)
void startRendering (bool cancelRunningJob)
void cancelRendering ()
bool isRendering () const
Public Attributes
std::function< void(bool success)> onRenderingFinished
std::atomic< double > progress {}
Constructor & Destructor Documentation
ClipBouncer()
foleys::ClipBouncer::ClipBouncer (VideoEngine & engine)
Member Function Documentation
setOutputFile()
void foleys::ClipBouncer::setOutputFile (juce::File file)
getOutputFile()
juce::File foleys::ClipBouncer::getOutputFile () const
setClipToRender()
void foleys::ClipBouncer::setClipToRender (std::shared_ptr< AVClip > clip)
setVideoSettings()
void foleys::ClipBouncer::setVideoSettings (const VideoStreamSettings & settings)
setAudioSettings()
void foleys::ClipBouncer::setAudioSettings (const AudioStreamSettings & settings)
startRendering()
void foleys::ClipBouncer::startRendering (bool cancelRunningJob)
References foleys::AVFormatManager::createClipWriter(), foleys::AudioStreamSettings::defaultNumSamples, foleys::VideoEngine::getFormatManager(), foleys::VideoEngine::getThreadPool(), progress, and foleys::AudioStreamSettings::timebase.
cancelRendering()
void foleys::ClipBouncer::cancelRendering ()
References foleys::VideoEngine::getThreadPool(), and onRenderingFinished.
isRendering()
bool foleys::ClipBouncer::isRendering () const
Member Data Documentation
onRenderingFinished
std::function<void(bool success)> foleys::ClipBouncer::onRenderingFinished
Referenced by cancelRendering().
progress
std::atomic<double> foleys::ClipBouncer::progress {}
Referenced by startRendering().
The documentation for this class was generated from the following files:
ClipBouncer.h
ClipBouncer.cpp