foleys_video_engine: foleys::PanningAudioProcessor Class Reference
foleys::PanningAudioProcessor Class Reference
This class provides a simple stereo panner.
Public Member Functions
juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout ()
PanningAudioProcessor ()
void prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock) override
void processBlock (juce::AudioBuffer< float > &buffer, juce::MidiBuffer &midiMessages) override
bool isBusesLayoutSupported (const juce::AudioProcessor::BusesLayout &layout) const override
double getTailLengthSeconds () const override
bool acceptsMidi () const override
bool producesMidi () const override
const juce::String getName () const override
void releaseResources () override
juce::AudioProcessorEditor * createEditor () override
bool hasEditor () const override
int getNumPrograms () override
int getCurrentProgram () override
void setCurrentProgram (int index) override
const juce::String getProgramName (int index) override
void changeProgramName (int index, const juce::String &newName) override
void getStateInformation (juce::MemoryBlock &destData) override
void setStateInformation (const void *data, int sizeInBytes) override
Static Public Member Functions
static juce::String getPluginName ()
Detailed Description
This class provides a simple stereo panner.
You can use it to add in as default for each AVClip when it is added to a ComposedClip. This allows to use this for simple stereo setups, or to use your own processor instead, if you want more versatile panning methods.
Constructor & Destructor Documentation
PanningAudioProcessor()
foleys::PanningAudioProcessor::PanningAudioProcessor ()
Member Function Documentation
getPluginName()
static juce::String foleys::PanningAudioProcessor::getPluginName () static
Referenced by foleys::AudioPluginManager::AudioPluginManager(), and getName().
createParameterLayout()
juce::AudioProcessorValueTreeState::ParameterLayout foleys::PanningAudioProcessor::createParameterLayout ()
prepareToPlay()
void foleys::PanningAudioProcessor::prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock) override
processBlock()
void foleys::PanningAudioProcessor::processBlock (juce::AudioBuffer< float > & buffer, juce::MidiBuffer & midiMessages) override
isBusesLayoutSupported()
bool foleys::PanningAudioProcessor::isBusesLayoutSupported (const juce::AudioProcessor::BusesLayout & layout) const override
getTailLengthSeconds()
double foleys::PanningAudioProcessor::getTailLengthSeconds () const override
acceptsMidi()
bool foleys::PanningAudioProcessor::acceptsMidi () const override
producesMidi()
bool foleys::PanningAudioProcessor::producesMidi () const override
getName()
const juce::String foleys::PanningAudioProcessor::getName () const override
References getPluginName().
releaseResources()
void foleys::PanningAudioProcessor::releaseResources () override
createEditor()
juce::AudioProcessorEditor* foleys::PanningAudioProcessor::createEditor () override
hasEditor()
bool foleys::PanningAudioProcessor::hasEditor () const override
getNumPrograms()
int foleys::PanningAudioProcessor::getNumPrograms () override
getCurrentProgram()
int foleys::PanningAudioProcessor::getCurrentProgram () override
setCurrentProgram()
void foleys::PanningAudioProcessor::setCurrentProgram (int index) override
getProgramName()
const juce::String foleys::PanningAudioProcessor::getProgramName (int index) override
changeProgramName()
void foleys::PanningAudioProcessor::changeProgramName (int index, const juce::String & newName) override
getStateInformation()
void foleys::PanningAudioProcessor::getStateInformation (juce::MemoryBlock & destData) override
setStateInformation()
void foleys::PanningAudioProcessor::setStateInformation (const void * data, int sizeInBytes) override
The documentation for this class was generated from the following file:
PanningAudioProcessor.h