foleys_video_engine: VideoParameterAutomation Class Reference
VideoParameterAutomation Class Reference
Controls the ProcessorParameters of a VideoProcessor.
Public Member Functions
VideoParameterAutomation (ProcessorController &controller, ProcessorParameter &parameter)
~VideoParameterAutomation () override
juce::String getName () const override
int getNumSteps () const override
void updateProcessor (double pts) override
void valueChanged (ProcessorParameter &parameter, double newValue) override
void gestureStarted (ProcessorParameter &parameter) override
void gestureFinished (ProcessorParameter &parameter) override
juce::String getText (float normalisedValue, int numDigits=0) const override
double getValueForText (const juce::String &text) const override
Public Member Functions inherited from ParameterAutomation
ParameterAutomation (ProcessorController &)
virtual ~ParameterAutomation ()=default
void setValue (double value)
void setValue (double pts, double value)
void addKeyframe (double pts, double value)
void setKeyframe (size_t index, double pts, double value)
double getValueForTime (double pts) const
double getValue () const
void startAutomationGesture ()
void finishAutomationGesture ()
const std::map< double, double > & getKeyframes () const
void loadFromValueTree (const juce::ValueTree &state)
void saveToValueTree (juce::ValueTree &state, juce::UndoManager *undo)
Additional Inherited Members
Protected Attributes inherited from ParameterAutomation
ProcessorController & controller
bool gestureInProgress = false
Detailed Description
Controls the ProcessorParameters of a VideoProcessor.
Constructor & Destructor Documentation
VideoParameterAutomation()
VideoParameterAutomation (ProcessorController & controller, ProcessorParameter & parameter)
~VideoParameterAutomation()
~VideoParameterAutomation () override
References ProcessorParameter::removeListener().
Member Function Documentation
getName()
juce::String getName () const override virtual
Implements ParameterAutomation.
References ProcessorParameter::getName().
getNumSteps()
int getNumSteps () const override virtual
Implements ParameterAutomation.
References ProcessorParameter::getNumSteps().
updateProcessor()
void updateProcessor (double pts) override virtual
Implements ParameterAutomation.
References ParameterAutomation::gestureInProgress, ParameterAutomation::getValueForTime(), and ProcessorParameter::setNormalisedValue().
valueChanged()
void valueChanged (ProcessorParameter & parameter, double newValue) override
References ParameterAutomation::controller, ClipDescriptor::getCurrentPTS(), ProcessorController::getOwningClipDescriptor(), and ParameterAutomation::setValue().
gestureStarted()
void gestureStarted (ProcessorParameter & parameter) override
References ParameterAutomation::startAutomationGesture().
gestureFinished()
void gestureFinished (ProcessorParameter & parameter) override
References ParameterAutomation::finishAutomationGesture().
getText()
juce::String getText (float normalisedValue, int numDigits = 0) const override virtual
Implements ParameterAutomation.
References ProcessorParameter::getText().
getValueForText()
double getValueForText (const juce::String & text) const override virtual
Implements ParameterAutomation.
References ProcessorParameter::getValueForText().
The documentation for this class was generated from the following files:
foleys_ParameterAutomation.h
foleys_ParameterAutomation.cpp