foleys_video_engine: http_multiclient.c File Reference
http_multiclient.c File Reference
Functions
int main (int argc, char **argv)
Detailed Description
libavformat multi-client network API usage example.
Function Documentation
main()
int main (int argc, char ** argv)
References av_dict_set(), av_err2str, av_log_set_level(), AV_LOG_TRACE, AVERROR, avformat_network_init(), avio_accept(), AVIO_FLAG_WRITE, avio_open2(), and client.