foleys_video_engine: resampling_audio.c File Reference
resampling_audio.c File Reference
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References AV_CH_LAYOUT_STEREO, AV_CH_LAYOUT_SURROUND, av_get_channel_layout_nb_channels(), av_opt_set_int(), av_opt_set_sample_fmt(), av_rescale_rnd(), AV_ROUND_UP, AV_SAMPLE_FMT_DBL, AV_SAMPLE_FMT_S16, av_samples_alloc_array_and_samples(), AVERROR, swr_alloc(), and swr_init().