foleys_video_engine: scaling_video.c File Reference
scaling_video.c File Reference
Functions
int main (int argc, char **argv)
Detailed Description
libswscale API use example.
Function Documentation
main()
int main (int argc, char ** argv)
References av_get_pix_fmt_name(), av_image_alloc(), av_parse_video_size(), AV_PIX_FMT_RGB24, AV_PIX_FMT_YUV420P, AVERROR, SWS_BILINEAR, and sws_getContext().