foleys_video_engine: foleys::ClipDescriptor Class Reference
foleys::ClipDescriptor Class Reference
The ClipDescriptor configures the placement of each clip to be used in compositing the ComposedClip.
Classes
struct AudioProcessorHolder
Public Member Functions
ClipDescriptor (ComposedClip &owner, std::shared_ptr< AVClip > clip)
ClipDescriptor (ComposedClip &owner, juce::ValueTree state)
juce::String getDescription () const
void setDescription (const juce::String &name)
double getStart () const
start of the clip in seconds
int64_t getStartInSamples () const
void setStart (double start)
double getLength () const
length of the clip in seconds
int64_t getLengthInSamples () const
void setLength (double length)
double getOffset () const
offset in seconds into the media
int64_t getOffsetInSamples () const
void setOffset (double offset)
int getVideoLine () const
void setVideoLine (int line)
int getAudioLine () const
void setAudioLine (int line)
juce::ValueTree & getStatusTree ()
void updateSampleCounts ()
void addAudioProcessor (std::unique_ptr< AudioProcessorHolder > processor, int index=-1)
void addAudioProcessor (std::unique_ptr< juce::AudioProcessor > processor, int index=-1)
void removeAudioProcessor (int index)
ComposedClip & getOwningClip ()
Public Attributes
std::shared_ptr< AVClip > clip
std::vector< std::unique_ptr< AudioProcessorHolder > > audioProcessors
Detailed Description
The ClipDescriptor configures the placement of each clip to be used in compositing the ComposedClip.
Constructor & Destructor Documentation
ClipDescriptor() [1/2]
foleys::ClipDescriptor::ClipDescriptor (ComposedClip & owner, std::shared_ptr< AVClip > clip)
References clip.
ClipDescriptor() [2/2]
foleys::ClipDescriptor::ClipDescriptor (ComposedClip & owner, juce::ValueTree state)
References foleys::AVClip::getVideoEngine().
Member Function Documentation
getDescription()
juce::String foleys::ClipDescriptor::getDescription () const
setDescription()
void foleys::ClipDescriptor::setDescription (const juce::String & name)
getStart()
double foleys::ClipDescriptor::getStart () const
start of the clip in seconds
getStartInSamples()
int64_t foleys::ClipDescriptor::getStartInSamples () const
setStart()
void foleys::ClipDescriptor::setStart (double start)
References foleys::ComposedClip::getUndoManager().
getLength()
double foleys::ClipDescriptor::getLength () const
length of the clip in seconds
getLengthInSamples()
int64_t foleys::ClipDescriptor::getLengthInSamples () const
setLength()
void foleys::ClipDescriptor::setLength (double length)
References foleys::ComposedClip::getUndoManager().
getOffset()
double foleys::ClipDescriptor::getOffset () const
offset in seconds into the media
getOffsetInSamples()
int64_t foleys::ClipDescriptor::getOffsetInSamples () const
setOffset()
void foleys::ClipDescriptor::setOffset (double offset)
References foleys::ComposedClip::getUndoManager().
getVideoLine()
int foleys::ClipDescriptor::getVideoLine () const
setVideoLine()
void foleys::ClipDescriptor::setVideoLine (int line)
References foleys::ComposedClip::getUndoManager().
getAudioLine()
int foleys::ClipDescriptor::getAudioLine () const
setAudioLine()
void foleys::ClipDescriptor::setAudioLine (int line)
References addAudioProcessor(), foleys::ComposedClip::getUndoManager(), removeAudioProcessor(), and updateSampleCounts().
getStatusTree()
juce::ValueTree & foleys::ClipDescriptor::getStatusTree ()
updateSampleCounts()
void foleys::ClipDescriptor::updateSampleCounts ()
References clip.
Referenced by setAudioLine().
addAudioProcessor() [1/2]
void foleys::ClipDescriptor::addAudioProcessor (std::unique_ptr< AudioProcessorHolder > processor, int index = -1)
References audioProcessors, foleys::ComposedClip::getCallbackLock(), foleys::ComposedClip::getDefaultBufferSize(), foleys::ClipDescriptor::AudioProcessorHolder::getProcessorState(), foleys::ComposedClip::getSampleRate(), foleys::ComposedClip::getUndoManager(), and foleys::ClipDescriptor::AudioProcessorHolder::processor.
Referenced by addAudioProcessor(), and setAudioLine().
addAudioProcessor() [2/2]
void foleys::ClipDescriptor::addAudioProcessor (std::unique_ptr< juce::AudioProcessor > processor, int index = -1)
References addAudioProcessor().
removeAudioProcessor()
void foleys::ClipDescriptor::removeAudioProcessor (int index)
References audioProcessors, and foleys::ComposedClip::getCallbackLock().
Referenced by setAudioLine().
getOwningClip()
ComposedClip & foleys::ClipDescriptor::getOwningClip ()
Member Data Documentation
clip
std::shared_ptr<AVClip> foleys::ClipDescriptor::clip
Referenced by ClipDescriptor(), and updateSampleCounts().
audioProcessors
std::vector<std::unique_ptr<AudioProcessorHolder> > foleys::ClipDescriptor::audioProcessors
Referenced by addAudioProcessor(), and removeAudioProcessor().
The documentation for this class was generated from the following files:
ClipDescriptor.h
ClipDescriptor.cpp